---
- name: If beegfs_state is present
  include_tasks: create.yml
  when: beegfs_state | lower == "present"

- name: If beegfs_state is absent
  include_tasks: destroy.yml
  when: beegfs_state | lower == "absent"
...
