---
- name: Install packages for BeeGFS management server
  package:
    name: beegfs-mgmtd
    state: "{{ beegfs_package_action }}"
  become: true
  notify: Restart BeeGFS mgmt service

- name: Configure interfaces in mgmt config file
  lineinfile:
    dest: "/etc/beegfs/beegfs-mgmtd.toml"
    regexp: "^# interfaces"
    line: "interfaces = {{ beegfs_interfaces }}"
  become: true

- name: Configure quota enable in mgmt config file
  lineinfile:
    dest: "/etc/beegfs/beegfs-mgmtd.toml"
    regexp: "^# quota-enable"
    line: "quota-enable = true"
  become: true

- name: Run management service setup script
  command: "/opt/beegfs/sbin/beegfs-mgmtd --init"
  args:
    creates: "/var/lib/beegfs/mgmtd.sqlite"
  become: true
  notify: Restart BeeGFS mgmt service
...
